services:
  web:
    build: .
    volumes:
      - .:/app
      - uploads_data:/app/uploads
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///./sql_app.db
    restart: always

volumes:
  uploads_data:
